config:
  width: 400
  height: 400
  exposure_rate: 0.0008
  wave_mode: false
  pixel_size: 1

scene:
  objects:
    # Повёрнутая призма
    - shape: triangle
      material: glass
      params:
        ax: 200
        ay: 80
        bx: 300
        by: 255
        cx: 100
        cy: 255
        rotated_by: 34

    # Лампочка 
    - shape: rect
      material: glow
      params:
        min_x: 50
        max_x: 50
        min_y: 130
        max_y: 170

    - shape: rect
      material: wall
      params:
        min_x: 0
        max_x: 49
        min_y: 126
        max_y: 175

    - shape: rect
      material: wall
      params:
        min_x: 45
        max_x: 65
        min_y: 172
        max_y: 175

    - shape: rect
      material: wall
      params:
        min_x: 45
        max_x: 65
        min_y: 126
        max_y: 129

    # Левая стена
    - shape: rect
      material: wall
      params:
        min_x: 0
        max_x: 2
        min_y: 0
        max_y: 400

    # Правая стена
    - shape: rect
      material: wall
      params:
        min_x: 398
        max_x: 400
        min_y: 0
        max_y: 400

    # Верхняя стена
    - shape: rect
      material: wall
      params:
        min_x: 0
        max_x: 400
        min_y: 0
        max_y: 2

    # Нижняя стена
    - shape: rect
      material: wall
      params:
        min_x: 0
        max_x: 400
        min_y: 398
        max_y: 400